server:
  port: 8089

spring:
  application:
    name: "app"
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ${spring.application.name}
      client-id: ${spring.application.name}-group
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
