spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: duytc
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
