version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/Mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: duytc
    ports:
      - "3306:3306"
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - /Users/duytc/Documents/Docker/Docker-data/redis:/data

