
spring:
  application:
    name: orders
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"
      state-dir: /tmp/kafka-streams/
      application-id: ${spring.application.name}
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 1811